# Site settings
title: Clean Blog
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "/startbootstrap-clean-blog-jekyll"
url: "http://startbootstrap.com"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
